### ISSUE TITLE
MQTT Smart home architecture

### ISSUE THREAD

**Issue by nanosonde** [pakerfeldt/knx-mqtt-bridge#1]
Hi!
Have you considered adopting the MQTT smart home architecture provided [here](https://github.com/mqtt-smarthome/mqtt-smarthome/blob/master/Architecture.md)?
A lot of projects of the style "xxx2mqtt" already follow this, although it is not official though.

The original author passed away unfortunately. He also created hm2mqtt, knx2mqtt based on Java. 
As there seem to be more developers using node.js, nobody seems to care about those Java based projects anymore. Fortunately, node.js replacements have been created by guys like you.

**Comment by pakerfeldt** [comment]
I'm not familiar to that architecture but it doesn't sound unreasonable and to some extent it's already pretty close. I will have this in mind for the future.

**Comment by pakerfeldt** [comment]
I'm afraid I won't be implementing this architecture.
