### ISSUE TITLE
Not a an issue more I reboot question

### ISSUE THREAD

**Issue by leffrh** [pakerfeldt/knx-mqtt-bridge#15]
Hi,

I'm very happy with this bridge!
But when i have a power loss or server reboot (Ubuntu) i can't get it connected automatically, help would be appreciated .

Thanks

**Comment by pakerfeldt** [comment]
This is not really enough information to help you unfortunately. Try to be more specific.

Is the problem that you don't know how to start the bridge automatically after a reboot or is the problem that the bridge itself starts but cannot connect to KNX?

**Comment by leffrh** [comment]
> This is not really enough information to help you unfortunately. Try to be more specific.
> 
> Is the problem that you don't know how to start the bridge automatically after a reboot or is the problem that the bridge itself starts but cannot connect to KNX?

Yes, I don't know how to start the bridge automatically after a reboot. I couln't find this on the net. I'm a linux beginner

**Comment by pakerfeldt** [comment]
You will have better success finding an answer in other forums than this I think. Some pointers to get you started:

https://serverfault.com/questions/363208/best-way-to-start-a-program-at-boot-on-ubuntu-server
https://ccm.net/computing/linux/2043-execute-a-script-at-startup-and-shutdown-on-ubuntu/

Myself, I'm running knx-mqtt-bridge as a docker container using docker-compose, but that's maybe an even more complex setup if you're a beginner on linux.

**Comment by joostn** [comment]
Create a file /etc/systemd/system/knx-mqtt-bridge.service :

```
[Unit]
Description=knx-mqtt-bridge
After=network.target
After=network-online.service

[Service]
Type=simple
User=knxmqttbridge
ExecStartPre=/bin/sleep 5
Environment=KNX_MQTT_CONFIG=/etc/knx-mqtt-bridge/config.yaml
ExecStart=/bin/bash -c "cd /knx-mqtt-bridge && node src/knx-mqtt.js && exit 1"
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
Then do
```systemctl enable knx-mqtt-bridge```
to have it start at boot and
```systemctl start knx-mqtt-bridge```
to start it now.

```journalctl -u knx-mqtt-bridge```
will show you the logs.

**Comment by joostn** [comment]
BTW this assumes it is living in /knx-mqtt-bridge. Otherwise change the 'cd' part above. And it will be running as user 'knxmqttbridge' (see the User line)

BTW2 those links above are outdated; you would use systemd today. See for example:
[https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6](https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6)

BTW3: @pakerfeldt thanks for creating this! I've happily been using it for some time.

**Comment by leffrh** [comment]
> Create a file /etc/systemd/system/knx-mqtt-bridge.service :
> 
> ```
> [Unit]
> Description=knx-mqtt-bridge
> After=network.target
> After=network-online.service
> 
> [Service]
> Type=simple
> User=knxmqttbridge
> ExecStartPre=/bin/sleep 5
> Environment=KNX_MQTT_CONFIG=/etc/knx-mqtt-bridge/config.yaml
> ExecStart=/bin/bash -c "cd /knx-mqtt-bridge && node src/knx-mqtt.js && exit 1"
> Restart=on-failure
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Then do `systemctl enable knx-mqtt-bridge` to have it start at boot and `systemctl start knx-mqtt-bridge` to start it now.
> 
> `journalctl -u knx-mqtt-bridge` will show you the logs.

I used npm install -g knx-mqtt-bridge to install .
I'm not sure where to point ExecStart= to

Thanks

**Comment by joostn** [comment]
You managed to manually start knx-mqtt-bridge? The same command can be put into ExecStart.

It's probably located in /usr/lib/node_modules/knx-mqtt-bridge/

**Comment by leffrh** [comment]
Hi,

due to an holiday i was not able to reply sooner.
I start from /home/username KNX_MQTT_CONFIG=knxconfig.yaml knx-mqtt-bridge (yaml and knx.xml files are located here)

couldnt trace  /usr/lib/node_modules/knx-mqtt-bridge/

Ubuntu version : 22.04

I can reinstall if needed

> You managed to manually start knx-mqtt-bridge? The same command can be put into ExecStart.
> 
> It's probably located in /usr/lib/node_modules/knx-mqtt-bridge/

Hi,

due to an holiday i was not able to reply sooner.
I start from /home/username KNX_MQTT_CONFIG=knxconfig.yaml knx-mqtt-bridge (yaml and knx.xml files are located here)

couldnt trace  /usr/lib/node_modules/knx-mqtt-bridge/

Ubuntu version : 22.04

I can reinstall if needed

**Comment by joostn** [comment]
Well then that command is what you should put in ExecStart. ExecStart is what's executed on boot.

**Comment by leffrh** [comment]
Hi,

found this in the log file : systemctl status knx-mqtt-bridge.service


× knx-mqtt-bridge.service - knx-mqtt-bridge
     Loaded: loaded (/etc/systemd/system/knx-mqtt-bridge.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-11-07 10:10:25 UTC; 15s ago
    Process: 88929 ExecStartPre=/bin/sleep 5 (code=exited, status=217/USER)
        CPU: 1ms

Nov 07 10:10:25 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 10:10:25 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 10:10:25 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 10:10:25 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 10:10:25 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 10:10:25 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 5.
Nov 07 10:10:25 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 10:10:25 knxbridge systemd[1]: knx-mqtt-bridge.service: Start request repeated too quickly.
Nov 07 10:10:25 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 10:10:25 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.

Extra logs from journal:

-- Boot 455ba8f61ec947558a29e8a2b3712bd0 --
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 1.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 2.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 3.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 4.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[859]: knx-mqtt-bridge.service: Failed to determine user credentials: No such process
Nov 07 18:38:00 knxbridge systemd[859]: knx-mqtt-bridge.service: Failed at step USER spawning /bin/sleep: No such process
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 5.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Start request repeated too quickly.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
lines 602-623/624 100%
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 3.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 4.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: Starting knx-mqtt-bridge...
Nov 07 18:38:00 knxbridge systemd[859]: knx-mqtt-bridge.service: Failed to determine user credentials: No such process
Nov 07 18:38:00 knxbridge systemd[859]: knx-mqtt-bridge.service: Failed at step USER spawning /bin/sleep: No such process
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Control process exited, code=exited, status=217/USER
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Failed with result 'exit-code'.
Nov 07 18:38:00 knxbridge systemd[1]: Failed to start knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Scheduled restart job, restart counter is at 5.
Nov 07 18:38:00 knxbridge systemd[1]: Stopped knx-mqtt-bridge.
Nov 07 18:38:00 knxbridge systemd[1]: knx-mqtt-bridge.service: Start request repeated too quickly.
lines 602-622/624 100%


Any ideas ?
