### ISSUE TITLE
knx-mqtt-bridge searches for knx.xml in root directory

### ISSUE THREAD

**Issue by darkspirit510** [pakerfeldt/knx-mqtt-bridge#16]
Hi!

The config.y[a]ml is automatically added in the `/config` directory. I also placed my `knx.xml` in this directory, but knx-mqtt-bridge reported "file not found". It is actually looking for the file in `/`. Is there a reason why it does not use `/config` as base directory? If you prefer, could you at least add this to the readme 🙈

Edit: Forgot to mention - I'm using your dockerfile.

Thanks!

Sascha

**Comment by pakerfeldt** [comment]
I've changed the default directory in the example config to `/config/knx.xml`.
