### ISSUE TITLE
Provide group address names as topics

### ISSUE THREAD

**Issue by nanosonde** [pakerfeldt/knx-mqtt-bridge#4]
Also for debugging purposes it would be nice to also have the topics with group address names available.
They could be derived from the ETS XML export file as well.

Example for the group address 3/2/1: 
Main name 3: Light
Mid name 3: Status
Sub name 3: Kitchen Light Status

knx/3/2/1 -> knx/Light/Status/Kitchen Light Status

**Comment by pakerfeldt** [comment]
Sure, this should be doable. How would you envision it to work? A configuration to publish to the named topic instead of using the numeric group address?

**Comment by nanosonde** [comment]
Back from vacation. :)

Why not add have both (numeric and named) at the same time?
