### ISSUE TITLE
No ETS export file?

### ISSUE THREAD

**Issue by giggo** [pakerfeldt/knx-mqtt-bridge#5]
The README indicates that knx-mqtt-bridge can be used without an ETS export file. If I do not specify one in config.yaml I get:

root@raspberrypi:/home/pi/knx-mqtt-bridge# KNX_MQTT_CONFIG=config.yaml knx-mqtt-bridge
[info] "2019-01-23T21:53:11.034Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.1'
warn: Could not read ETS export file undefined, TypeError: path must be a string or Buffer
/usr/lib/node_modules/knx-mqtt-bridge/src/knx-mqtt.js:46
    let gad = gadArray[1] + "/" + gadArray[2] + "/" + gadArray[3];
...

Is there a way to run the bridge without ETS export file?

**Comment by pakerfeldt** [comment]
It's meant to work without ETS file, definitely. I will look into this as soon as I get some spare time.
In the meantime, try referring to an empty export file. Something like:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<GroupAddress-Export xmlns="http://knx.org/xml/ga-export/01">
</GroupAddress-Export>
```

**Comment by giggo** [comment]
WIth an empty export file I get:
```
root@raspberrypi:/home/pi/knx-mqtt-bridge# ./startempty.sh
[info] "2019-01-28T19:34:06.975Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.1'
warn: Could not read ETS export file /home/pi/knx-mqtt-bridge/empty.xml, TypeError: Cannot read property 'length' of undefined
...
```

**Comment by pakerfeldt** [comment]
Just tried it myself and you can indeed run it without the ETS file. What you see in the log is just a warning and can be ignored.

**Comment by pakerfeldt** [comment]
Here's an example output after running without `etsExport` configuration:
```
[info] "2019-01-28T20:31:54.498Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.0'
warn: Could not read ETS export file undefined, TypeError: path must be a string or Buffer {"meta":[]}
info: KNX connected
verbose: 2019-01-28 20:31:55 **** KNX EVENT: GroupValue_Response, dst: 4/1/1, value: "{\"value\":{\"type\":\"Buffer\",\"data\":[0,30]},\"response\":true}" {"meta":[]}
verbose: 2019-01-28 20:31:56 **** KNX EVENT: GroupValue_Write, dst: 4/1/2, value: "{\"value\":{\"type\":\"Buffer\",\"data\":[1,104]}}" {"meta":[]}
verbose: 2019-01-28 20:31:57 **** KNX EVENT: GroupValue_Response, dst: 4/1/1, value: "{\"value\":{\"type\":\"Buffer\",\"data\":[0,55]},\"response\":true}" {"meta":[]}
```

**Comment by giggo** [comment]
Hm. Thanks for checking.
In this case I run into a different issue:

```
root@raspberrypi:/home/pi/knx-mqtt-bridge# ./startwithoutetsexport.sh
[info] "2019-01-28T21:20:04.870Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.1'
warn: Could not read ETS export file undefined, TypeError: path must be a string or Buffer
info: KNX connected
info: MQTT connected
silly: Received MQTT message on topic knx/status/3/3/10 with value {"knx_src_addr":"2.1.53","knx_dpt":"9.001","val":21.42}
/usr/lib/node_modules/knx-mqtt-bridge/src/knx-mqtt.js:46
    let gad = gadArray[1] + "/" + gadArray[2] + "/" + gadArray[3];
                      ^

TypeError: Cannot read property '1' of null
    at MqttClient.<anonymous> (/usr/lib/node_modules/knx-mqtt-bridge/src/knx-mqtt.js:46:23)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)
    at MqttClient._handlePublish (/usr/lib/node_modules/knx-mqtt-bridge/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/usr/lib/node_modules/knx-mqtt-bridge/node_modules/mqtt/lib/client.js:336:12)
    at work (/usr/lib/node_modules/knx-mqtt-bridge/node_modules/mqtt/lib/client.js:292:12)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by pakerfeldt** [comment]
You would have to describe what you're trying to accomplish. I can see that you receive an MQTT message on knx/status/3/3/10. Who's sending that? The topic format is incorrect but even more problematic, it doesn't look like it's targeted to this bridge. The value wouldn't be parsable by the bridge even if the topic was correct.

**Comment by giggo** [comment]
Stupid me. I had retained topics from another KNX-MQTT bridge on my broker. I thought I had deleted them...
