### ISSUE TITLE
Publish messages sent to the KNX bus also via MQTT

### ISSUE THREAD

**Issue by mruettgers** [pakerfeldt/knx-mqtt-bridge#9]
Messages that have been sent to the KNX bus by the bridge itself are currently not being published via MQTT.
Although this might be a limitation of the underlying kns.js library we should be able to handle it in the bridge.

I will provide a PR for this feature request as soon as there is some spare time for implementing it.

An example where this feature would be helpful is when using different MQTT clients, one for sending metrics (in my case temperature measurements received via 1-Wire for being used by my heating actuator) to the KNX-Bus, and another MQTT-Client that is used as the metric collector of a time series database (InfluxDB in my case). Currently just the metrics from other KNX sensors are being collected, not those sent out by the bridge.

Or as another example I make use of the motion sensor of my door bell (Doorbird) via its LAN-API. The motion events are sent to the KNX-Bus to allow actuators react on them but should also be available to other MQTT-subscribers the same way (including mapping back to its group address name because I don't want to maintain such mappings on multiple places).

**Comment by pakerfeldt** [comment]
Sounds like a good addition. Feel free to provide a PR when ready.

**Comment by mruettgers** [comment]
This issue just came up again, but it looks like it has already been solved in the knx.js library: https://bitbucket.org/ekarak/knx.js/pull-requests/47.
It should not be a big deal to set the ` localEchoInTunneling` option to ` true`, maybe depending on our own config setting to keep backward compabatility.

**Comment by mruettgers** [comment]
It's even easier than I thought 😉. We can already specify knx.js options in the configuration file.
